name: .NET Build & Analysis

on:
  push:
    paths:
      - "BackEndGearShop/**"
  pull_request:
    paths:
      - "BackEndGearShop/**"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./BackEndGearShop

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Check code formatting
        run: dotnet format --verify-no-changes

      - name: Build and run analyzers
        run: dotnet build --no-restore
